#!/usr/bin/env bash

apc_version="3.1.9"

curl -L "http://pecl.php.net/get/APC-/${apc_version}.tgz" \
    | tar xzv

cd APC-${apc_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
            --enable-apc --enable-apc-debug

make
make install
#echo "extension=apc.so" > "$PREFIX/etc/conf.d/apc.ini"

cat << EOF > "$PREFIX/etc/conf.d/apc.ini"
extension="apc.so"
[apc]
apc.stat = "0"
apc.max_file_size = "1M"
apc.localcache = "1"
apc.localcache.size = "256"
apc.shm_segments = "1"
apc.ttl = "3600"
apc.user_ttl = "7200"
apc.gc_ttl = "3600"
apc.cache_by_default = "1"
apc.filters = ""
apc.write_lock = "1"
apc.num_files_hint= "512"
apc.user_entries_hint="4096"
apc.shm_size = "256M"
apc.mmap_file_mask=/tmp/apc.XXXXXX
apc.include_once_override = "0"
apc.file_update_protection="2"
apc.canonicalize = "1"
apc.report_autofilter="0"
apc.stat_ctime="0"
;This should be used when you are finished with PHP file changes.
;As you must clear the APC cache to recompile already cached files.
;If you are still developing, set this to 1.
apc.stat="0"
EOF
